### ISSUE TITLE
Additional Datasets for testing

### ISSUE THREAD

**Issue by vaiju1981** [romanpro23/NeuralNetworkCPU#3]
Hi Roman,

Thanks for uploading  apple_orange, ciraf, mnist_batch, svhn and quick_draw.

Can you point me or upload other datasets
1. Flickr
2. Imagenet 1K, 200, 250, 500
3. Tiny Imagenet
4. imdb
5. nlp dataset.

If you can point to links. I can download it myself.

**Comment by romanpro23** [comment]
Hello.
I added tiny imagenet and imbd dataset as link in readme file. Another datasets I can't find.
